# Generated by Django 5.0.6 on 2024-06-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
